name: Publish Docker Image App

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dkfz-unite/unite-commands
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Publish
        run: dotnet publish -c Release -r linux-x64 -o ./publish -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:DebugType=None --self-contained
      - name: Rename
        run: mv ./publish/Unite.Commands.Web ./publish/commands
      - name: ls
        run: ls -la

    
  build-and-push-image:
    needs: build-and-publish-app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            USER=${{ github.actor }}
            TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: ${{env.REGISTRY}}/${{github.repository}}
